name = "blobs-api"
main = "src/worker.ts"
compatibility_date = "2023-09-04"

[vars]
environment = 'production'

[[tail_consumers]]
service = 'ingest-worker'

[[kv_namespaces]]
binding = "secrets"
id = "9c05b646c17b4bc19b1ba41e9bf55cc0"
preview_id = "9c05b646c17b4bc19b1ba41e9bf55cc0"

[durable_objects]
bindings = [{ name = "tunnels", class_name = "Tunnel" }]
[[migrations]]
tag = "v0"
new_classes = ["Tunnel"]
