name = "blobs-api"
main = "src/worker.ts"
compatibility_date = "2023-07-24"

[vars]
environment = 'production'
allowedOrigins = ["https://blob.city"]

[[kv_namespaces]]
binding = "metadata"
id = "9c05b646c17b4bc19b1ba41e9bf55cc0"
preview_id = "9c05b646c17b4bc19b1ba41e9bf55cc0"

[durable_objects]
bindings = [{ name = "sessions", class_name = "Session" }]
[[migrations]]
tag = "v0"
new_classes = ["Session"]
